name: takemeals
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.0.0
  http: ^1.1.2
  intl: ^0.18.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  # flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
    - family: Miriam Libre
      fonts: 
        - asset: assets/fonts/MiriamLibreBold.ttf
          weight: 700
        - asset: assets/fonts/MiriamLibreRegular.ttf
          weight: 400

